version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/app/models:/app/app/models:ro
    environment:
      - MODEL_PATH=/app/app/models/multimodal_model.pth
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  extension:
    build:
      context: ./extension
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./extension:/app
    restart: unless-stopped
    depends_on:
      - backend