"""Initial migration.

Revision ID: 7f9e5d92c76b
Revises: 
Create Date: 2024-10-12 13:16:44.388866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9e5d92c76b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_maintenance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.String(length=80), nullable=False),
    sa.Column('issue_details', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tires', sa.String(length=100), nullable=True),
    sa.Column('brakes', sa.String(length=100), nullable=True),
    sa.Column('oil', sa.String(length=100), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('lights', sa.String(length=100), nullable=True),
    sa.Column('engine_performance', sa.String(length=100), nullable=True),
    sa.Column('transmission_fluid', sa.String(length=100), nullable=True),
    sa.Column('battery_charger', sa.String(length=100), nullable=True),
    sa.Column('brake_pads', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_update_bus_id'), 'maintenance_update', ['bus_id'], unique=False)
    op.create_table('monthly_maintenance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_maintenance_record')
    op.drop_index(op.f('ix_maintenance_update_bus_id'), table_name='maintenance_update')
    op.drop_table('maintenance_update')
    op.drop_table('driver_query')
    op.drop_table('daily_maintenance_record')
    # ### end Alembic commands ###
